pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - BUILD_NAME="$DRONE_REPO_NAME:drone-build-$DRONE_BUILD_NUMBER"
      - CONTAINER_SUFFIX="$DRONE_REPO_NAME-$DRONE_BUILD_NUMBER"
      - NAME_COMMIT="$REPO/$DRONE_REPO_NAME:$DRONE_COMMIT"
      - NAME_BRANCH="$REPO/$DRONE_REPO_NAME:$(echo $DRONE_BRANCH | sed 's/\//_/')"
      - docker build -t "$BUILD_NAME" . --build-arg NPM_TOKEN=$NPM_TOKEN
      - trap 'docker rmi -f "$NAME_COMMIT" "$BUILD_NAME"' EXIT
      - '[[ -f bin/test ]] && docker run --rm --name "testing-$CONTAINER_SUFFIX" "$BUILD_NAME" bin/test'
      - docker tag "$BUILD_NAME" "$NAME_COMMIT"
      - docker tag "$BUILD_NAME" "$NAME_BRANCH"
      - docker push "$NAME_COMMIT"
      - docker push "$NAME_BRANCH"
    environment:
      - REPO=docker.billy.dk
